### ISSUE TITLE
No loading information when opening the explorer

### ISSUE THREAD

**Issue by ecamellini** [BikeRoutes/Explorer#9]
As a user, I expect the app to let me know it's loading content so that I know it's working properly and I just have to wait a few seconds.

## How to reproduce

1. Open the explorer: https://bikeroutes.github.io/Explorer/
2. Wait for the map to load

### Expected
While waiting, I see something informing me that the page is loading.

## Actual
I see a white screen and think that the app doesn't work properly.

**Comment by FrancescoCioria** [comment]
now, with the service worker, the app (scripts, css, html..) and every GET request is cache-first => the page loads VERY fast
